### ISSUE TITLE
feature request: quit on the n-th "pod deleted"

### ISSUE THREAD

**Issue by gretel** [knight42/kt#5]
using a script (in a deployment pipeline) i would love to start `kt` and check on the logs as long as a pod is running - and continue with the script when "pod deleted" happens - have `kt` exit.

in my case, the terminated pod exists until i start the pipeline again, so it will be the first thing to happen. therefore, exiting on the second time would work for me.

virtual example:

```shell
$ kt -n ca --qond 2 kaniko-kerykeion
- [kaniko-kerykeion-99vf2] pod deleted
...
- [kaniko-kerykeion-21xad] pod deleted
quitting.
```

**Comment by knight42** [comment]
I know this is useful in your case, but IMHO it might be quite limited, i.e. many other people may not encounter this problem.

Regarding this case, I think we could provide a flag(`--exit-with-pods` maybe?) which can have `kt` exit if all pods it watched are deleted(IMO this may be a more common use case), and then you could run a script like
```bash
for i in 0 1; do
  kt -n ca --tail 0 --exit-with-pods kaniko-kerykeion
done
```

**Comment by gretel** [comment]
@knight42 thanks, ya that is an edge case. the above should work for me!

**Comment by knight42** [comment]
@gretel could you try the latest release?

**Comment by gretel** [comment]
@knight42 it's working fine, thank you!

now, how about 

```
 --exit-with-container build
```

to exit when a particular container of a pod exits?
